#!/bin/sh

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "will"
sudo scutil --set HostName "local"
sudo scutil --set LocalHostName "localhost"

# Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#----------------------------------------------------------------------------------------#
# Homebrew
#----------------------------------------------------------------------------------------#
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade
brew doctor

#----------------------------------------------------------------------------------------#
# Brewfile
#----------------------------------------------------------------------------------------#
brew tap Homebrew/bundle
brew bundle
mas upgrade

brew missing

brew cask cleanup
brew cleanup --force
rm -rf /Library/Caches/Homebrew/*

#----------------------------------------------------------------------------------------#
# Move dotfiles
#----------------------------------------------------------------------------------------#
cd ~/ && rcup -d .dotfiles -x Brewfile
